image: python:3.8

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.cache/pipenv

before_script:
  - python3 --version
  - pip install pipenv

cache:
  paths:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR

test:
  script:
    - pip install pipenv
    - pipenv install --dev
    - PYTHONPATH=$(PWD):$PYTHONPATH pipenv run pytest
